version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: testcodex-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: testcodex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres-data:
